//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintBoxMain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintBoxMain.ResourcesMessages", typeof(ResourcesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap arrow_down_disabled {
            get {
                object obj = ResourceManager.GetObject("arrow_down_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_up_disabled {
            get {
                object obj = ResourceManager.GetObject("arrow_up_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_backspace_disabled {
            get {
                object obj = ResourceManager.GetObject("button_backspace_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap code_button_cancel {
            get {
                object obj = ResourceManager.GetObject("code_button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap code_button_cancel_disabled {
            get {
                object obj = ResourceManager.GetObject("code_button_cancel_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap code_button_disabled {
            get {
                object obj = ResourceManager.GetObject("code_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap code_button_ok_disabled {
            get {
                object obj = ResourceManager.GetObject("code_button_ok_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap four_sheets_on_page_disabled {
            get {
                object obj = ResourceManager.GetObject("four_sheets_on_page_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap four_sheets_on_page_selected_disabled {
            get {
                object obj = ResourceManager.GetObject("four_sheets_on_page_selected_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font face=&quot;century gothic&quot; color=&quot;#000000&quot; size=&quot;2&quot;&gt;&lt;p align=&quot;left&quot;&gt;
        ///&lt;p align=&quot;center&quot;&gt;Як користуватися терміналом?&lt;p align=&quot;center&quot;&gt;
        ///&lt;p align=&quot;center&quot;&gt;
        ///&lt;/font&gt;&lt;font face=&quot;century gothic&quot; color=&quot;#FF0000&quot; size=&quot;2&quot;&gt;&lt;p align=&quot;left&quot;&gt;&lt;u&gt;PrintBox&lt;/font&gt;&lt;font face=&quot;century gothic&quot; color=&quot;#000000&quot; size=&quot;2&quot;&gt;&lt;/u&gt; - це термінал автоматичного друку. Він друкує документи формату Microsoft Word з будь-яких USB-носіїв.&lt;p align=&quot;left&quot;&gt;
        ///&lt;p align=&quot;left&quot;&gt;
        ///Щоб надрукувати документ:&lt;p align=&quot;left&quot;&gt;
        /// 1. Вставте флешку в порт з  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string instructionHTML {
            get {
                return ResourceManager.GetString("instructionHTML", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap keyboard_back {
            get {
                object obj = ResourceManager.GetObject("keyboard_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_back_clicked {
            get {
                object obj = ResourceManager.GetObject("keyboard_back_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_back_disabled {
            get {
                object obj = ResourceManager.GetObject("keyboard_back_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_button {
            get {
                object obj = ResourceManager.GetObject("keyboard_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_button_clicked {
            get {
                object obj = ResourceManager.GetObject("keyboard_button_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_button_disabled {
            get {
                object obj = ResourceManager.GetObject("keyboard_button_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_cancel {
            get {
                object obj = ResourceManager.GetObject("keyboard_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_cancel_disabled {
            get {
                object obj = ResourceManager.GetObject("keyboard_cancel_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_ok {
            get {
                object obj = ResourceManager.GetObject("keyboard_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_ok_disabled {
            get {
                object obj = ResourceManager.GetObject("keyboard_ok_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap keyboard_panel_fon {
            get {
                object obj = ResourceManager.GetObject("keyboard_panel_fon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap maintenance_minimize_disabled {
            get {
                object obj = ResourceManager.GetObject("maintenance_minimize_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap maintenance_no {
            get {
                object obj = ResourceManager.GetObject("maintenance_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap maintenance_no_disabled {
            get {
                object obj = ResourceManager.GetObject("maintenance_no_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap maintenance_yes {
            get {
                object obj = ResourceManager.GetObject("maintenance_yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap maintenance_yes_disabled {
            get {
                object obj = ResourceManager.GetObject("maintenance_yes_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap message_fon {
            get {
                object obj = ResourceManager.GetObject("message_fon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap money_params_info_fon {
            get {
                object obj = ResourceManager.GetObject("money_params_info_fon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте,виникла помилка обробки даних..
        /// </summary>
        public static string msgErrorHappened {
            get {
                return ResourceManager.GetString("msgErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте,виникла помилка відкриття файлу..
        /// </summary>
        public static string msgErrorHappenedWhileOpeningFile {
            get {
                return ResourceManager.GetString("msgErrorHappenedWhileOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте,виникла помилка відправки SMS. Зверніться до служби підтримки..
        /// </summary>
        public static string msgErrorHappenedWhileSendingSms {
            get {
                return ResourceManager.GetString("msgErrorHappenedWhileSendingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірні параметри друку..
        /// </summary>
        public static string msgInvalidPrintParams {
            get {
                return ResourceManager.GetString("msgInvalidPrintParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний діапазон сторінок..
        /// </summary>
        public static string msgInvalidPrintRange {
            get {
                return ResourceManager.GetString("msgInvalidPrintRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можна надрукувати більше 150 сторніок за один сеанс..
        /// </summary>
        public static string msgMoreThan150PagesForPrint {
            get {
                return ResourceManager.GetString("msgMoreThan150PagesForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, в цьому терміналі скінчився папір. Ми спробуємо виправити це найближчим часом..
        /// </summary>
        public static string msgNoPaper {
            get {
                return ResourceManager.GetString("msgNoPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостатньо коштів для друку..
        /// </summary>
        public static string msgNotEnoughMoney {
            get {
                return ResourceManager.GetString("msgNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостатньо паперу для друку. В терміналі залишилось {0} сторінок..
        /// </summary>
        public static string msgNotEnoughPagesForPrint {
            get {
                return ResourceManager.GetString("msgNotEnoughPagesForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, виникла помилка принтера..
        /// </summary>
        public static string msgPrinterIsNotReady {
            get {
                return ResourceManager.GetString("msgPrinterIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, не вдалося з&apos;єднатися з сервером. Будь-ласка, спробуйте пізніше..
        /// </summary>
        public static string msgServerUnavailable {
            get {
                return ResourceManager.GetString("msgServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На номер {0} відправлено SMS із паролем для доступу до рахунку..
        /// </summary>
        public static string msgSmsWithPassSent {
            get {
                return ResourceManager.GetString("msgSmsWithPassSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, термінал не працює..
        /// </summary>
        public static string msgTerminalIsNotWorking {
            get {
                return ResourceManager.GetString("msgTerminalIsNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, занадто довге ім&apos;я файлу..
        /// </summary>
        public static string msgTooLongFileName {
            get {
                return ResourceManager.GetString("msgTooLongFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат файлу. Підтримуються формати .doc/.docx..
        /// </summary>
        public static string msgUnsupportedFileType {
            get {
                return ResourceManager.GetString("msgUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобільний оператор з кодом {0} не підтримується..
        /// </summary>
        public static string msgUnsupportedMobileOperator {
            get {
                return ResourceManager.GetString("msgUnsupportedMobileOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний код поповнення..
        /// </summary>
        public static string msgWrongCode {
            get {
                return ResourceManager.GetString("msgWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний пароль..
        /// </summary>
        public static string msgWrongPassword {
            get {
                return ResourceManager.GetString("msgWrongPassword", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap one_sheet_on_page_disabled {
            get {
                object obj = ResourceManager.GetObject("one_sheet_on_page_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap one_sheet_on_page_selected_disabled {
            get {
                object obj = ResourceManager.GetObject("one_sheet_on_page_selected_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_back {
            get {
                object obj = ResourceManager.GetObject("preprint_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_back_disabled {
            get {
                object obj = ResourceManager.GetObject("preprint_back_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_cancel {
            get {
                object obj = ResourceManager.GetObject("preprint_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_cancel_disabled {
            get {
                object obj = ResourceManager.GetObject("preprint_cancel_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_next {
            get {
                object obj = ResourceManager.GetObject("preprint_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_next_disabled {
            get {
                object obj = ResourceManager.GetObject("preprint_next_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_print {
            get {
                object obj = ResourceManager.GetObject("preprint_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap preprint_print_disabled {
            get {
                object obj = ResourceManager.GetObject("preprint_print_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_down {
            get {
                object obj = ResourceManager.GetObject("scroll_button_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_down_clicked {
            get {
                object obj = ResourceManager.GetObject("scroll_button_down_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_down_disabled {
            get {
                object obj = ResourceManager.GetObject("scroll_button_down_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_up {
            get {
                object obj = ResourceManager.GetObject("scroll_button_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_up_clicked {
            get {
                object obj = ResourceManager.GetObject("scroll_button_up_clicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap scroll_button_up_disabled {
            get {
                object obj = ResourceManager.GetObject("scroll_button_up_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap two_sheets_on_page_disabled {
            get {
                object obj = ResourceManager.GetObject("two_sheets_on_page_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap two_sheets_on_page_selected_disabled {
            get {
                object obj = ResourceManager.GetObject("two_sheets_on_page_selected_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap txt_document {
            get {
                object obj = ResourceManager.GetObject("txt_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат A4.
        /// </summary>
        public static string txtA4Format {
            get {
                return ResourceManager.GetString("txtA4Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увага! Для відновлення пароля зверніться до служби підтримки..
        /// </summary>
        public static string txtAttentionGeneral {
            get {
                return ResourceManager.GetString("txtAttentionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увага! Повідомлення відправляється тільки один раз при першому вводі номера. Для відновлення пароля зверніться до служби підтримки..
        /// </summary>
        public static string txtAttentionPhone {
            get {
                return ResourceManager.GetString("txtAttentionPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID термінала: &lt;!--BoxID--&gt;.
        /// </summary>
        public static string txtBoxID {
            get {
                return ResourceManager.GetString("txtBoxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінок у лотку: &lt;!--paperLeft--&gt;.
        /// </summary>
        public static string txtCleanPaperLeft {
            get {
                return ResourceManager.GetString("txtCleanPaperLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копій: &lt;!--copyNumber--&gt;.
        /// </summary>
        public static string txtCopyNumber {
            get {
                return ResourceManager.GetString("txtCopyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка &lt;!--currentPage--&gt; з &lt;!--totalPagesInDocument--&gt;.
        /// </summary>
        public static string txtCurrentPageInfo {
            get {
                return ResourceManager.GetString("txtCurrentPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інкасація проведена успішно?.
        /// </summary>
        public static string txtIsEncashmentOk {
            get {
                return ResourceManager.GetString("txtIsEncashmentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуговування проведено успішно?.
        /// </summary>
        public static string txtIsMaintenanceOk {
            get {
                return ResourceManager.GetString("txtIsMaintenanceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесені гроші повернуто на рахунок..
        /// </summary>
        public static string txtMoneyReturnedToBalance {
            get {
                return ResourceManager.GetString("txtMoneyReturnedToBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінок на аркуші: &lt;!--pagesPerSheet--&gt;.
        /// </summary>
        public static string txtPagesPerSheet {
            get {
                return ResourceManager.GetString("txtPagesPerSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усього друкувати сторінок: &lt;!--pagesTotal--&gt;.
        /// </summary>
        public static string txtPagesTotal {
            get {
                return ResourceManager.GetString("txtPagesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль, отриманий у SMS-повідомленні..
        /// </summary>
        public static string txtPasswordFirstTimeTooltip {
            get {
                return ResourceManager.GetString("txtPasswordFirstTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть Ваш пароль..
        /// </summary>
        public static string txtPasswordGeneralTooltip {
            get {
                return ResourceManager.GetString("txtPasswordGeneralTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть номер Вашого телефону. На нього буде віправлено SMS-повідомлення із паролем для доступу до особистого рахунку..
        /// </summary>
        public static string txtPhoneTooltip {
            get {
                return ResourceManager.GetString("txtPhoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друк формату А4.
        /// </summary>
        public static string txtPrint {
            get {
                return ResourceManager.GetString("txtPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, під час друку трапилась помилка..
        /// </summary>
        public static string txtPrintError {
            get {
                return ResourceManager.GetString("txtPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надруковано &lt;!--pages_printed_now--&gt; із &lt;!--pages_to_print--&gt; стор..
        /// </summary>
        public static string txtPrinting {
            get {
                return ResourceManager.GetString("txtPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Іде друк. Не витягуйте флешку..
        /// </summary>
        public static string txtPrintingWarning {
            get {
                return ResourceManager.GetString("txtPrintingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друкувати сторінки з &lt;!--pageFrom--&gt; по &lt;!--pageTo--&gt;.
        /// </summary>
        public static string txtPrintPagesFromTo {
            get {
                return ResourceManager.GetString("txtPrintPagesFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 коп./стор..
        /// </summary>
        public static string txtPrintPrice {
            get {
                return ResourceManager.GetString("txtPrintPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друк успішно завершено..
        /// </summary>
        public static string txtPrintSuccess {
            get {
                return ResourceManager.GetString("txtPrintSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для початку роботи вставте флешку..
        /// </summary>
        public static string txtStartWorkMessage {
            get {
                return ResourceManager.GetString("txtStartWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дякуємо за користування терміналом..
        /// </summary>
        public static string txtThanksForUsingPrintBox {
            get {
                return ResourceManager.GetString("txtThanksForUsingPrintBox", resourceCulture);
            }
        }
    }
}
